### ISSUE TITLE
Ultimate Doom doom.wad -> XBOX doom.wad

### ISSUE THREAD

**Issue by fabiangreffrath** [Doom-Utils/iwad-patches#1]
Hi,

I have once created a binary patch to "upgrade" the ordinary The Ultimate Doom doom.wad file to the XBOX variant, which contains the notorious E1M10: Sewers map. I needed this to implement support for this specific map in Crispy Doom.

It can be found here:

http://www.greffrath.com/~fabian/d1_ud_xbox

Cheers,

Fabian

PS: I have about every possible IWAD somewhere on my disk. Tell me if you are looking for other patches.

**Comment by chungy** [comment]
Thanks. I used only the versions that I could get access to, but it would be nice to gather more patches. I've added this one :)

The Xbox version should also have a special copy of Doom 2, fwiw. (And maybe the Master Levels are different?)

**Comment by fabiangreffrath** [comment]
Yes, I also have the Xbox version of doom2.wad.  I also have the Xbox360 Version of doom2.wad (but not the Xbox360 version of doom.wad, unfortunately) and the rare French doom2f.wad v1.8. Please find then here:

http://greffrath.com/~fabian/d2_19_xbox
http://greffrath.com/~fabian/d2_19_xbox360
http://greffrath.com/~fabian/d2_19_18f
- Fabian

PS: I don't know about the Master Levels. All I know is that there is a stand-alone masterlevels.wad available on exclusively on PSN. However, I don't think it is possible to provide a patch between this and the 20 wads bundle. :/

**Comment by chungy** [comment]
Thanks again. About 1.8f, were doom.exe and setup.exe also translated at all?

Your xbox360 patch appears to be the BFG version of the game, at least according to the checksums on the [Doom Wiki](http://doomwiki.org/wiki/DOOM2.WAD). I've named the patches accordingly, if this is in error, feel free to tell me or send a PR ;)

Master Levels could be tricky. Maybe it's possible to "cat *.wad > masterlevels.wad" on the individual ones, then create a patch? It would introduce a lot of hairy work to use it, but might still be workable. (Edit: Okay, that would actually be a method of going from 20 WADs to 1, but the reverse is trickier. Most archive commands (such as tar and zip) don't necessarily store files by order of file name, either, and also vary depending on ownership and modes... or it could also be a workaround)

**Comment by fabiangreffrath** [comment]
> About 1.8f, were doom.exe and setup.exe also translated at all?

Honestly, I don't know. I have exchanged these IWADs with other source port authors so we could check if our ports would run with them. We never exchanged any supplemental files at all.

> Your xbox360 patch appears to be the BFG version

Yes, indeed it is the BFG Edition.

> Maybe it's possible to "cat *.wad > masterlevels.wad" on the individual ones, then create a patch?

This is possible, but you need the exact order for the patch to be of a reasonable size. Please try this

```
$ cat attack.wad canyon.wad catwalk.wad combine.wad fistula.wad garrison.wad manor.wad paradox.wad subspace.wad subterra.wad ttrap.wad virgil.wad minos.wad bloodsea.wad mephisto.wad nessus.wad geryon.wad vesperas.wad blacktwr.wad teeth.wad > master.wad
```

and then apply the following patch
http://greffrath.com/~fabian/master

At the moment this method is only one-directional, but you could split the frankenWAD that the reverse patch would create by the file sizes as given in the Wiki. ;)

**Comment by chungy** [comment]
> This is possible, but you need the exact order for the patch to be of a reasonable size.

This is an advantage of VCDIFF (which xdelta3 implements), it can figure out how to move the data around. Its patch is about the same size whether they're specially-ordered or not :-)

Thanks for it though. I can't think of much to do for going the other direction in an OS-agnostic way (which was an unwritten rule for the rest). I almost wonder if it's worth bothering, it seems a bit unlikely to me that somebody would own only the PSN version and try to use it on the PC. Might just make a script that uses dd to extract little portions; or _maybe_ depend on deutex to extract the levels and repatch those. Personally I'm favoring the dd idea.

**Comment by fabiangreffrath** [comment]
It should be possible to have the files in a uncompressed .tar archive.

**Comment by chungy** [comment]
@fabiangreffrath tar might not be the best idea, it's difficult to generate them deterministically from a shell script, but I can think of a workaround for that using a temporary git repository. Zip _might_ fare better, but I don't know how fragile the format is between implementations.

Of the two, I might use the git imtermediary method.

**Comment by chungy** [comment]
I've added scripts in 859891d490836f911312ded309b1c0c28929d69c to go between the Master Levels versions. It might be a bit rough still, but it's what I currently came up with.
