### ISSUE TITLE
Suggestion: add vcdiff for other unity WADs

### ISSUE THREAD

**Issue by rygar997** [Doom-Utils/iwad-patches#13]
There're Unity versions of:
- Double Impact 
- SIGIL
I thnik it could be good idea do add vcdiff also for his WADs.

**Comment by chungy** [comment]
Since these are free PWADs in the first place, maybe it'd be easier to host them somewhere (would idgames accept such a thing? I don't know)

**Comment by rygar997** [comment]
Downloads for Unity WADs are not available. Take a look here:
https://www.wad-archive.com/wad/SIGIL-(Unity)

**Comment by elephantflea** [comment]
@rygar997 it only wasn't there by mistake. It is available for download

**Comment by chungy** [comment]
Seems like the updated Double Impact isn't available yet, but regardless, I think I am satisfied with the resolution so far.

I mainly maintain this repository for those WAD files that can't be distributed, legally, in whole in the first place. Downloading a complete file is a lot easier than patching them. This is mostly just IWADs for various games.
