### ISSUE TITLE
1.9-to-bethsoft.vcdiff seems to be an invalid patch

### ISSUE THREAD

**Issue by diabolucion** [Doom-Utils/iwad-patches#16]
First of all, my doom2_1.9.wad file is not tampered with.

```
E:\doom\temp>sha1sum -b doom2_1.9.wad
7ec7652fcfce8ddc6e801839291f0e28ef1d5ae7 *doom2_1.9.wad
```

Having said this, 1.9-to-bethsoft.vcdiff seems to be an invalid patch. Or at least, it is not a patch from doom2_1.9.wad to doom2_bethsoft.wad.

```
E:\doom\temp>xdelta3-3.0.11-x86_64 -d -s doom2_1.9.wad 1.9-to-bethsoft.vcdiff doom2_bethsoft.wad
xdelta3: target window checksum mismatch: XD3_INVALID_INPUT
xdelta3: normally this indicates that the source file is incorrect
xdelta3: please verify the source file with sha1sum or equivalent
```

Of course, I have double-checked the syntax of xdelta3 to apply a patch.

```
E:\doom\temp>xdelta3-3.0.11-x86_64 -help
<snipped>
apply patch:

  xdelta3.exe -d -s old_file delta_file decoded_new_file
<snipped>
```

**Comment by chungy** [comment]
We've sometimes seem things like this before with versions of xdelta3 that are too old. Try getting version 3.1.0 and see if it works then.

**Comment by diabolucion** [comment]
No success. I have obtained 3.1.0 for Win64 from the repo linked below and the issue persists.

[https://github.com/jmacd/xdelta-gpl/releases/tag/v3.1.0](https://github.com/jmacd/xdelta-gpl/releases/tag/v3.1.0)

```
E:\doom\temp>xdelta3-3.1.0-x86_64 -d -s doom2_1.9.wad 1.9-to-bethsoft.vcdiff doom2_bethsoft.wad
xdelta3: target window checksum mismatch: XD3_INVALID_INPUT
xdelta3: normally this indicates that the source file is incorrect
xdelta3: please verify the source file with sha1sum or equivalent
```

**Comment by chungy** [comment]
Looking into it myself, I seem to have the same issue actually. I probably didn't even test it when I was given the patches, oops.

@elephantflea can you try to remake them? or even email me the WAD?

**Comment by elephantflea** [comment]
@chungy I have created a pull request
