### ISSUE TITLE
New version of nerve.wad

### ISSUE THREAD

**Issue by diabolucion** [Doom-Utils/iwad-patches#19]
It seems like there is a new variant of nerve.wad. Its SHA-1 hash is _2c5c4aa07eea8820a65dbf282d8b6d8358bb74fa_, and its time stamp (as per its HTTP headers) is _15 Jul 2020 14:55:39 GMT_.

Unfortunately, I cannot provide a proper xdelta3 patch as Termux does not offer that tool, as far as I am aware. Thus, I have uploaded few par2 recovery blocks to convert the classic nerve.wad file (_3451288383fb16e196f273d9f85d58c1fda97bf4_) to this one. Obviously, I have tested them.

```
$ sha1sum -b nerve.wad
3451288383fb16e196f273d9f85d58c1fda97bf4 *nerve.wad
$ par2 repair -q -q nerve.wad.vol0+5.par2
$ sha1sum -b nerve.wad
2c5c4aa07eea8820a65dbf282d8b6d8358bb74fa *nerve.wad
$
```

Download: https://drive.google.com/file/d/1Vb3yM-jngy98AYpZZOde6U-nJ4S2gccU/

**Comment by chungy** [comment]
Thanks, I'll check it out as soon as I can.

What release is this from? Unity ports or...?

**Comment by diabolucion** [comment]
This release is for / from Unity ports, indeed.

**Comment by landfillbaby** [comment]
it's exactly the same but with the unity DMAPINFO, i checked with both HWadTools waddiff and by deleting said chunk from the patched version in SLADE3 and checking the files were the same again

**Comment by landfillbaby** [comment]
also i'm currently working on a PR to add xdelta3 to Termux, i'm surprised it wasn't in there already

**Comment by landfillbaby** [comment]
ok so. the difference between the unity 1.1 version and this new version is that all the level names are prefixed by e.g. "Level 3: "
@diabolucion what is the unity version number? i don't have access to a pc right now

**Comment by landfillbaby** [comment]
i'll just say it's 1.2
