### ISSUE TITLE
NERVE readme discrepancy?

### ISSUE THREAD

**Issue by buvk** [Doom-Utils/iwad-patches#23]
The readme for NERVE states the following:

> On July 15th, 2020, another update added prefixes (e.g. “Level 1:”) to
> 
> the map names in the DMAPINFO chunk.  We call this version “Unity 1.2.”
> 
> What release you grabbed nerve.wad out of should be evident, but the
> known-good SHA1s are documented here:
> 3451288383fb16e196f273d9f85d58c1fda97bf4  nerve_bfg.wad
> 321e951f6cc6e9d51bc16eac53e0d001f0f3f338  nerve_unity1.1.wad
> 2c5c4aa07eea8820a65dbf282d8b6d8358bb74fa  nerve_unity1.2.wad

I opened up nerve_unity1.1.wad and nerve_unity1.2.wad in SLADE, and it looks like 1.2 actually removed  the "Level X:" prefixes from DMAPINFO.

**Comment by landfillbaby** [comment]
that might be my fault, i may have swapped them by accident. checkout before my commits and see if the 1.1 has the prefixes or not. sorry. i would do it myself but i'm busy with something else right now
