### ISSUE TITLE
New unity versions

### ISSUE THREAD

**Issue by buvk** [Doom-Utils/iwad-patches#24]
The unity versions have been updated again.

doom.wad
SHA-1: 2a8a1ce0f29497a2781b2902c76115fd60d8bbf8

doom2.wad
SHA-1: 9574851209c9dfbede56db0dee0660ecd51e6150

nerve.wad
SHA-1: 6ab960ae23430ca2ced7db3edd8075b7e0158f26

plutonia.wad
SHA-1: 20fd23ee410c466b263a741bbd53bbef573ab47d

tnt.wad
SHA-1: ca0f0495a6c2813b49620202774c56560d6d7621

The major changes here are widescreen TITLEPIC and INTERPIC.

**Comment by diabolucion** [comment]
I have created and uploaded a few of PAR2 recovery blocks, as I cannot run xdelta3 and GitHub Desktop for reasons, currently. Sorry for the inconvenience.

https://drive.google.com/file/d/1jKbiU8feqpeExOg3jGN2-15YMdlmo7YV/view?usp=sharing

Before (input files, which are required):
```
9b07b02ab3c275a6a7570c3f73cc20d63a0e3833 *doom.wad
7ec7652fcfce8ddc6e801839291f0e28ef1d5ae7 *doom2.wad
3451288383fb16e196f273d9f85d58c1fda97bf4 *nerve.wad
90361e2a538d2388506657252ae41aceeb1ba360 *plutonia.wad
9fbc66aedef7fe3bae0986cdb9323d2b8db4c9d3 *tnt.wad
```

After (output files):
```
2a8a1ce0f29497a2781b2902c76115fd60d8bbf8 *doom.wad
9574851209c9dfbede56db0dee0660ecd51e6150 *doom2.wad
6ab960ae23430ca2ced7db3edd8075b7e0158f26 *nerve.wad
20fd23ee410c466b263a741bbd53bbef573ab47d *plutonia.wad
ca0f0495a6c2813b49620202774c56560d6d7621 *tnt.wad
```

**Comment by chungy** [comment]
Thanks :)
