### ISSUE TITLE
Strife on Nintendo Switch

### ISSUE THREAD

**Issue by chungy** [Doom-Utils/iwad-patches#25]
If anyone knows how to data-mine a Nintendo Switch title, it seems likely to me that at least SVE.wad is altered in the new release (what appears to be new assets for the weapon scroll). I doubt strife1.wad nor voices.wad are altered, but it wouldn't hurt to double check them anyway.

**Comment by elephantflea** [comment]
I have extracted WADs from the unity releases on the switch so will have a go if I can source the files

**Comment by chungy** [comment]
[Strife is a separate game entirely...](https://www.nintendo.com/games/detail/strife-veteran-edition-switch/)

**Comment by elephantflea** [comment]
Yea but I imagine extracting the files wouldn't be much different unless it is wrapped up in some custom stuff

**Comment by chungy** [comment]
Closed by #26
