### ISSUE TITLE
Possible new variant of TNT.WAD and PLUTONIA.WAD

### ISSUE THREAD

**Issue by diabolucion** [Doom-Utils/iwad-patches#27]
Hello guys.

It turns out that three out of four IWADs of the European release of _Doom Classic Complete_ (NPEB-01014) differ from the ones bundled with the American release (NPUB-30808). These are their SHA-1 sums:

DOOM2.WAD: f1b6ba94352d53f646b67c01d2da88c5c40e3179
TNT.WAD: 5066833da047117241cdda05a708b009eb266c91
PLUTONIA.WAD: 85c3517434135a5886111b324955f9288c01046c

Whilst that doom2.wad may be familiar (it matches doom2_bethsoft.wad, after all), both tnt.wad and plutonia.wad are still undocumented, as far as I am aware.

[patches_usa_to_eur.zip](https://github.com/Doom-Utils/iwad-patches/files/5968825/patches_usa_to_eur.zip)

**Comment by chungy** [comment]
Great find!

Is this release found on Steam, or how did you come across it?

**Comment by diabolucion** [comment]
European release of _Doom Classic Complete_ for PS3, I may not link to the official pkg for obvious reasons.

https://i.imgur.com/jp3g1Qn.png

**Comment by chungy** [comment]
Fascinating :)

Thanks a lot for the patches!
