### ISSUE TITLE
Hexen v1.1 to "retail store beta"

### ISSUE THREAD

**Issue by fabiangreffrath** [Doom-Utils/iwad-patches#28]
@xttl provided some binary deltas here:
https://www.doomworld.com/forum/topic/121524-hexen-v11-to-retail-store-beta-downgrader/

**Comment by fabiangreffrath** [comment]
https://hilla.kapsi.fi/~vv/hex_up_down/

**Comment by chungy** [comment]
Seems I looked at the Doomworld thread at the same time as you. I've added what I think should be a complete set of files, thanks :)

**Comment by fabiangreffrath** [comment]
Great, thanks!
