### ISSUE TITLE
Please add Boom 2.0x and MBF

### ISSUE THREAD

**Issue by fabiangreffrath** [Doom-Utils/iwad-patches#29]
Could we please add all known releases of Boom and MBF? For one, judging from their versioning schema and from the close connection between id Software and TeamTNT at the time of their release, they are to be considered the semi-official successors of (the various versions of) Doom 1.9 (and of Boom in the case of MBF). Second, it would be nice to be able to check out this one repository and have all the official (and relevant semi-official) DOS engines available for use in e.g. DOSBOX in one place.

**Comment by chungy** [comment]
I don't think this repository is really an appropriate place for them, and all the binaries I know of are on idgames...

There is (some) source code in the historic-ports repo: https://github.com/Doom-Utils/historic-ports/commits/mbf

**Comment by chungy** [comment]
Maybe as an alternative, we can have a different repository hosting binaries of prominent/dead source ports?

**Comment by fabiangreffrath** [comment]
Not every prominent/dead source port played the same role that Boom and MBF did. Anyway, I understand if you are not going to add them, it was just an idea. 😉

**Comment by chungy** [comment]
I believe anything that isn't an official release of the game engines is out-of-scope. We have some rare ones, but presumably everything here is what was compiled by someone at sometime by id, Raven, or Rogue.
