### ISSUE TITLE
extras.wad from the Unity rerelase

### ISSUE THREAD

**Issue by grcancelliere** [Doom-Utils/iwad-patches#30]
The `extras.wad` included with the Unity rerelease of Doom 1 and Doom 2 had an update on September 3, 2020 [(doom wiki reference)](https://doomwiki.org/wiki/Extras.wad). I don't know if you're interested, since it's not techically an IWAD, but if you are I generated the vcdiff patches and tested them with my own version of extras.wad.

[extras.wad patches.zip](https://github.com/Doom-Utils/iwad-patches/files/8458446/extras.wad.patches.zip)

**Comment by chungy** [comment]
It'd fit in just fine with the philosophy of the repo (the name of it is already a bit outdated... see master levels and nerve.wad).

I didn't know there was another resources file with the Unity port, thanks for the info/files!
