### ISSUE TITLE
New version of nerve.wad for Unity version

### ISSUE THREAD

**Issue by Yarn366** [Doom-Utils/iwad-patches#31]
Id has once again updated the Unity version of No Rest for the Living. This time, it's an IWAD that includes all Doom 2 assets, save for most of the maps and anything else that nerve.wad previously replaced (although MAP11 is inexplicably included). This was probably done so that it can be played in Doom I (the Unity version, anyway).

The size of this new version is 15,569,321 bytes, and it contains 2,666 lumps.

CRC-32: 5990e558
MD5: 53d180803ae34b16a63c5f1c97faf562
SHA-1: 7bb0734f85b045dd41482c5e95b0ecbe1700fbcb

**Comment by grcancelliere** [comment]
@Yarn366 Thanks for checking! Here are the new patches to and from the BFG edition:

[unity_1.4 patches.zip](https://github.com/Doom-Utils/iwad-patches/files/10148199/unity_1.4.patches.zip)
