### ISSUE TITLE
add REKKR?

### ISSUE THREAD

**Issue by fabiangreffrath** [Doom-Utils/iwad-patches#32]
Hi,

it would be nice if one could convert back and forth between REKKR.wad, REKKRSA.wad and REKKRSL.wad (and their different versions, if any).

**Comment by chungy** [comment]
This one seems pretty clearly out of scope. Is it not a free PWAD? Why not just download it?

**Comment by fabiangreffrath** [comment]
There is also a stand-alone IWAD (REKKRSA.wad) and a commercial IWAD (REKKRSL.wad), that's why I was asking.

**Comment by chungy** [comment]
Huh, I didn't know that. If SL is the only for-pay version I don't think I'd be comfortable with sidestepping that.

**Comment by fabiangreffrath** [comment]
Fair enough, thanks!
