### ISSUE TITLE
doom2 update 1 bad sha

### ISSUE THREAD

**Issue by 7zxkv** [Doom-Utils/iwad-patches#39]
Hello,

I've looked at the sha1 of the latest doom2.wad with the latest update of october 3, and the hash you indicate ([here](https://github.com/Doom-Utils/iwad-patches/commit/70f996c56dd62b9a6912b78f2c79968c8191fd77)) is not the right one, it must be 3b6fe319fa7ac64567520d960f977fde9c5818c8 .  (7ec7652fcfce8ddc6e801839291f0e28ef1d5ae7  is doom2 1.9 vanilla)

What's more, the name you gave is doom2_key_update1.wad instead of doom2_kex_update1.wad. However, to respect your logic (with doom64) I think you could have named them all like this: name_kex_1.1.wad (and the old name_kex_1.0.wad) even if this is just an almost cosmetic detail.

Thank you for your attention, good continuation

**Comment by chungy** [comment]
Thanks, I'll fix when I get home (or elephantflea does it, we'll see).

**Comment by chungy** [comment]
Fixed in 28730242573408932ad2a37838409a2bc1e547a0
