### ISSUE TITLE
Missing alternative Ultimate Doom executable

### ISSUE THREAD

**Issue by AXDOOMER** [Doom-Utils/iwad-patches#5]
There exist an alternative Ultimate Doom executable. It's pretty rare and I'm struggling to remember where to find it. The startup banner was either green or aqua.

**Comment by chungy** [comment]
I vaguely recall such a banner from a pre-release version of Ultimate Doom (when it was still called Doom: Special Edition?). I wouldn't be against adding it, but it would mark the first non-release version :)

**Comment by AXDOOMER** [comment]
If it was never released, how was it made available so people could put their hands on it? I don't believe it was made available through a leak or beta testing. Could it be on a Doom95 CD?

**Comment by chungy** [comment]
Using the word "vaguely" was a way to allow myself to completely wrong.

I am extremely intrigued by the possibility of an alternative existing, beta/leak/pre-release or even something like the alternate version of Final Doom. If you can find any information, or especially files, please let me know!

**Comment by AXDOOMER** [comment]
You are right about it being called "Doom: Special Edition", because I remember the same thing. I'll be searching some CDs, if I'm lucky, I'll find it.

**Comment by AXDOOMER** [comment]
Found it!

It was in the 2015 Romero release dump, in doom-maps.zip in the folder DoomMapsSE. 
You can get it here: https://archive.org/details/2015JohnRomeroDoomDump

It was documented when found and it's an incomplete Ultimate Doom executable, so I don't think it's worth adding it in your repo. It's dated 28 March 1995. 
https://tcrf.net/Proto:Doom_(PC,_1993)/Doom_1.9_Special_Edition

**Comment by chungy** [comment]
Thanks for the information. I think I'll agree with not putting it in this repo, given its status (and we don't even have a compiled equivalent doom.wad to go with it).

Is it at least documented anywhere on doomwiki.org?

**Comment by AXDOOMER** [comment]
Yes. 

https://doomwiki.org/wiki/The_Ultimate_Doom#Name
